### ISSUE TITLE
Cannot fetch new mails

### ISSUE THREAD

**Issue by tuxmartin** [freescout-help-desk/freescout#4182]
PHP version: 8.3
FreeScout version: 1.8.149
Database: MySQL / PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules:  No
I'm using docker image: `tiredofit/freescout:php8.3-1.17.81`

Today I discovered that I have a problem downloading email from one mailbox. I don't know exactly how long it takes.
I found the problem in version 1.8.145. I updated to 1.8.149 and it didn't help.

When I try to download emails in /system/tools, it doesn't do anything. However, there is no error in logs.
```
[2024-08-15 11:27:10] Mailbox: XXX
[2024-08-15 11:27:10] Folder: INBOX
[2024-08-15 11:27:10] Fetched: 0
<< * OK Seznam IMAP server ready
>> TAG1 LOGIN "xxxx@xxx.cz" "xxxxxxxxxxxxx"
<< TAG1 OK LOGIN Authentication succeeded
>> TAG2 LIST "" "*"
<< * LIST (\Noinferiors \HasNoChildren) "|" "INBOX"
<< * LIST (\Noinferiors \HasNoChildren \Sent) "|" "sent"
<< * LIST (\Noinferiors \HasNoChildren \Drafts) "|" "drafts"
<< * LIST (\Noinferiors \HasNoChildren \Archive) "|" "archive"
<< * LIST (\Noinferiors \HasNoChildren \Junk) "|" "spam"
<< * LIST (\Noinferiors \HasNoChildren \Trash) "|" "trash"
<< * LIST (\HasChildren) "|" "~Archive"
<< * LIST (\HasNoChildren) "|" "~Archive|2021"
<< * LIST (\HasNoChildren) "|" "Archiv"
<< TAG2 OK LIST complete
>> TAG3 SELECT "INBOX"
<< * 347 EXISTS
<< * 0 RECENT
<< * FLAGS (\Seen \Answered \Flagged \Deleted \Draft \Recent $Forwarded NonJunk Junk)
<< * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted $Forwarded \* NonJunk Junk)] Can bee changed permanently
<< * OK [UIDVALIDITY 1] UIDs validity number
<< * OK [UIDNEXT 2253] Predicted next UID
<< * OK [UNSEEN 345] The first unseen message MSN.
<< TAG3 OK [READ-WRITE] SELECT completed
>> TAG4 UID SEARCH SINCE "14-Aug-2024" UNSEEN
<< TAG4 NO SEARCH: mtd: internal error: Bad token (expecting date specification).
>> TAG5 LOGOUT
<< * BYE Thanks for your visit, have a nice day.
<< TAG5 OK LOGOUT Completed.
```

I'm using IMAP https://napoveda.seznam.cz/cz/email/imap-pop3-smtp/

I added the account to Thunderbird, and I normally see new emails there.

Please advise me on how to proceed.

**Comment by freescout-help** [comment]
https://freescout.net/blog/new-fetching-library/

**Comment by tuxmartin** [comment]
@freescout-help I tried to change SSL to TLS at page https://xxx.yyy.zzz/mailbox/connection-settings/3/incoming

For both SSL and TLS (previously I used SSL) I see green box with message `Connection established!` after click on `Check connection`. But I still can't fetch any emails. As you can see my previous debug log, FreeScout sucesfully connect to IMAP.

Is there any other ways how can I fix it? Can I downgrade FreeScout to version before 1.8.140?

**Comment by tuxmartin** [comment]
I just got back from version 1.8.149 on version 1.8.139 and everything started to work. I hope I didn't break anything.

I cannot understand why I can't fetch emails if connection test was succesfull...

**Comment by freescout-help** [comment]
Fixed in FreeScout v1.8.150

**Comment by tuxmartin** [comment]
I tried the lastest version `1.8.153` with `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING=true` and it's still broken.

Same problem with `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING=false`.

After restore backup ( `1.8.139`) everything is ok.

There is fetch log from  `1.8.153` :

```
[2024-10-02 14:04:40] Mailbox: Partnership XXX
[2024-10-02 14:04:40] Folder: INBOX
[2024-10-02 14:04:40] Fetched: 0
<< * OK Seznam IMAP server ready
>> TAG1 LOGIN "partnership@XXX.cz" "xxx"
<< TAG1 OK LOGIN Authentication succeeded
>> TAG2 LIST "" "*"
<< * LIST (\Noinferiors \HasNoChildren) "|" "INBOX"
<< * LIST (\Noinferiors \HasNoChildren \Sent) "|" "sent"
<< * LIST (\Noinferiors \HasNoChildren \Drafts) "|" "drafts"
<< * LIST (\Noinferiors \HasNoChildren) "|" "newsletters"
<< * LIST (\Noinferiors \HasNoChildren \Archive) "|" "archive"
<< * LIST (\Noinferiors \HasNoChildren \Junk) "|" "spam"
<< * LIST (\Noinferiors \HasNoChildren \Trash) "|" "trash"
<< TAG2 OK LIST complete
>> TAG3 SELECT "INBOX"
<< * 2 EXISTS
<< * 0 RECENT
<< * FLAGS (\Seen \Answered \Flagged \Deleted \Draft \Recent $Forwarded)
<< * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted $Forwarded \*)] Can bee changed permanently
<< * OK [UIDVALIDITY 1] UIDs validity number
<< * OK [UIDNEXT 4] Predicted next UID
<< * OK [UNSEEN 1] The first unseen message MSN.
<< TAG3 OK [READ-WRITE] SELECT completed
>> TAG4 UID SEARCH SINCE "29-Sep-2024" UNSEEN
<< TAG4 NO SEARCH: mtd: internal error: Bad token (expecting date specification).
>> TAG5 LOGOUT
<< * BYE Thanks for your visit, have a nice day.
<< TAG5 OK LOGOUT Completed.
```

@freescout-help what am I doing wrong?

**Comment by tuxmartin** [comment]
@freescout-help can you please help me?

**Comment by freescout-help** [comment]
Remove `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING` from your .env file.

**Comment by tuxmartin** [comment]
Hi @michalpulpan, Unfortunately not.  I'm still stuck on version 1.8.139 ☹️

**Comment by freescout-help** [comment]
@michalpulpan Do you have `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING=true` set in your .env file?
Can you share your IMAP communication log ("Manage » System » Tools", check "Debug" checkbox and click "Fetch Emails").

**Comment by michalpulpan** [comment]
> @michalpulpan Do you have `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING=true` set in your .env file? Can you share your IMAP communication log ("Manage » System » Tools", check "Debug" checkbox and click "Fetch Emails").
@freescout-help 

Thank you for a very quick response. So I've upgraded to the version 1.8.158 and set `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING=true ` This is my compose file:

```yaml
services:
  freescout-app:
    image: tiredofit/freescout:latest
    container_name: freescout-app
    user: root
    ports:
    - 8099:80
    links:
    - freescout-db
    volumes:
    - ./data:/www/html
    - ./logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    - DB_HOST=host
    - DB_NAME=name
    - DB_USER=user
    - DB_PASS=pass
    - SITE_URL=https://x.y.z
    - ADMIN_EMAIL=x@y.z
    - ADMIN_PASS=x
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=Europe/Prague
    - ENABLE_SSL_PROXY=TRUE
    - NGINX_ENABLE_FASTCGI_HTTPS=TRUE
    - APP_SINCE_WITHOUT_QUOTES_ON_FETCHING=true
    restart: always
```

And here is log from one inbox where I sent a new message, so for some reason, it should have at least one recent message
```
[2024-11-24 09:36:57] Fetching UNREAD emails for the last 1 days.
[2024-11-24 09:36:57] Mailbox: XXXXXX
[2024-11-24 09:36:57] Fetching: ALL
[2024-11-24 09:36:57] Folder: INBOX
[2024-11-24 09:36:59] Fetched: 0
<< * OK Seznam IMAP server ready
>> TAG1 LOGIN "x@y.z" "pass"
<< TAG1 OK LOGIN Authentication succeeded
>> TAG2 LIST "" "*"
<< * LIST (\Noinferiors \HasNoChildren) "|" "INBOX"
<< * LIST (\Noinferiors \HasNoChildren \Sent) "|" "sent"
<< * LIST (\Noinferiors \HasNoChildren \Drafts) "|" "drafts"
<< * LIST (\Noinferiors \HasNoChildren) "|" "newsletters"
<< * LIST (\Noinferiors \HasNoChildren \Archive) "|" "archive"
<< * LIST (\Noinferiors \HasNoChildren \Junk) "|" "spam"
<< * LIST (\Noinferiors \HasNoChildren \Trash) "|" "trash"
<< * LIST (\HasNoChildren) "|" "Sent Messages"
<< * LIST (\HasNoChildren) "|" "Deleted Messages"
<< TAG2 OK LIST complete
>> TAG3 SELECT "INBOX"
<< * 49274 EXISTS
<< * 0 RECENT
<< * FLAGS (\Seen \Answered \Flagged \Deleted \Draft \Recent $Forwarded $NotJunk Junk $Junk Forwarded $MailFlagBit0 $MailFlagBit2 NotJunk $MailFlagBit1)
<< * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted $Forwarded \* $NotJunk Junk $Junk Forwarded $MailFlagBit0 $MailFlagBit2 NotJunk $MailFlagBit1)] Can bee changed permanently
<< * OK [UIDVALIDITY 4] UIDs validity number
<< * OK [UIDNEXT 425912] Predicted next UID
<< * OK [UNSEEN 49274] The first unseen message MSN.
<< TAG3 OK [READ-WRITE] SELECT completed
>> TAG4 UID SEARCH SINCE "23-Nov-2024"
<< TAG4 NO SEARCH: mtd: internal error: Bad token (expecting date specification).
>> TAG5 LOGOUT
<< * BYE Thanks for your visit, have a nice day.
<< TAG5 OK LOGOUT Completed.
```

This is from my mailing client where I have the same inbox:
<img width="359" alt="Snímek obrazovky 2024-11-24 v 9 39 31" src="https://github.com/user-attachments/assets/38acbff1-3d88-40a1-a87f-ee458699954e">

**Comment by freescout-help** [comment]
Apparently Docker image does not support `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING` option. Can you create an issue in https://github.com/tiredofit/docker-freescout/issues

**Comment by michalpulpan** [comment]
> Apparently Docker image does not support `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING` option. Can you create an issue in https://github.com/tiredofit/docker-freescout/issues

Thank you for advice, it was really caused by docker image not supporting this env variable. We inserted the variable directly into .env file, recreated containers and it started to work similarly to older versions using manual fetch, but there is **still problem witch fetching using cron**.

When we try to fetch emails manually from "Manage » System » Tools", emails are fetched correctly, but when process is triggered by cron, no email is fetched whatsoever, but in system status, there is success message that last fetching was performed in XX:XX.

Have you got any idea what to do with this issue please? 
Thank you for your help!

**Comment by freescout-help** [comment]
Clear cache or kill all background jobs: https://github.com/freescout-help-desk/freescout/wiki/Background-Jobs

**Comment by michalpulpan** [comment]
> Clear cache or kill all background jobs: https://github.com/freescout-help-desk/freescout/wiki/Background-Jobs

Good point, helped to resolve it, thank you! 
@tuxmartin I can't really reproduce all the steps since my colleague did it, but I can now confirm that we're running 1.8.158 with Seznam.cz IMAP and everything works as expected.
