### ISSUE TITLE
Message is in "Assigned" folder but is not actually assigned to User - throwing error

### ISSUE THREAD

**Issue by ScottChampagne** [freescout-help-desk/freescout#4540]
We have several messages in the "Assigned" folder, but the message aren't actually assigned to a user.
<img width="1610" alt="Image" src="https://github.com/user-attachments/assets/b27fa225-f8be-4ab7-816d-3a235e79bc73" />

Clicking on them throws the following error

` ErrorException (E_ERROR)
Call to a member function getFullName() on null (View: /www/html/resources/views/conversations/view.blade.php)
Previous exceptions

    Call to a member function getFullName() on null (0)

                    `
Appears to be throwing on line 1086 of  /www/html/app/Conversation.php 
`            return $this->user->getFullName();`

-->

PHP version: php8.3-1.17.104
FreeScout version: 1.8.168
Database: PostgreSQL
Are you using CloudFlare:  No
Are you using non-official modules:  No

**Comment by freescout-help** [comment]
"Call to a member function getFullName() on null" - fixed in the `master` branch and will be published in the next release.

**Comment by ScottChampagne** [comment]
So, that handles the error to the exception of an “assigned” message being “unassigned”.

But, that doesn’t seem to fix the underlying issue of those messages shouldn’t be in that folder does it?

**Comment by freescout-help** [comment]
There is no way to tell what was the reason. Maybe something went wrong during deletion of some user.

**Comment by ScottChampagne** [comment]
There have been no active users that have been deleted. This is a fairly new install. I can think of only one user that was deleted and they were never an active user.

Either way, the emails in question were all created _after_ the deletion of any users.

**Comment by freescout-help** [comment]
So it's not clear what caused this and how to reproduce the issue. If someone will find out please share your insights.
