### ISSUE TITLE
Issue version 1.8.178 no more custom footer live chat

### ISSUE THREAD

**Issue by PeopleInside** [freescout-help-desk/freescout#4755]
PHP version: 8.4
FreeScout version: 1.8.178
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

After the update to 1.8.178 my custom live chat that I put on the footer portal.blade.php is no more showed.
I need resume the backup if this issue is not resolved, I lost my live chat widget

**Comment by PeopleInside** [comment]
The issue seems caused by the new line added
https://github.com/freescout-help-desk/freescout/blob/eab97711027fff4bce90ccd2e189cbc184fa0370/app/Misc/Helper.php#L976
I removed this line and all works back fine.

**Comment by freescout-help** [comment]
Can you describe how to reproduce the issue? Step-by-step.

**Comment by PeopleInside** [comment]
Sure, 
I use the [live helper chat](https://livehelperchat.com/) software for monitor the ticket and knowledge base page as well.
The same chat are used on my websites.

In the demo is possible take a embed code that is the script code to place where the chat should be showed.
For show the live chat in the knowledge base I edit the file /Modules/Knowledgebase/Resources/views/layouts/portal.balde.php where in the footer section I add the live chat code.

Same is done in the ticket page editing /Modules/EnsUserPortal/Resources/views/layouts/portal.balde.php

After your adding in the version 1.8.178 the live chat widget is no more showed due to the Content Security Policy.
I don't know how else solve just removing that line you added.

**Comment by freescout-help** [comment]
Add the following to the .env file and clear cache:
```
APP_CSP_SCRIPT_SRC="livehelperchat.com some-other-domain.org"
```

If it still does not work, open browser console and check Content-Security-Policy errors. Add to the `APP_CSP_SCRIPT_SRC` parameter all the the mentioned in errors domains separating them with the space.

**Comment by PeopleInside** [comment]
Tested and never work.
You new fix also in the issue https://github.com/freescout-help-desk/freescout/issues/4754 invalidate my fix to remove line 976

![Image](https://github.com/user-attachments/assets/041dfda3-abb8-4c84-8e33-a9e750ef9437)

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by PeopleInside** [comment]
Still not working also with this fix

![Image](https://github.com/user-attachments/assets/6643b14d-0646-4d31-a628-4b243da832a1)

**Comment by miroslavpechacek** [comment]
> Add the following to the .env file and clear cache:
> 
> ```
> APP_CSP_SCRIPT_SRC="livehelperchat.com some-other-domain.org"
> ```
> 
> If it still does not work, open browser console and check Content-Security-Policy errors. Add to the `APP_CSP_SCRIPT_SRC` parameter all the the mentioned in errors domains separating them with the space.

I am using freescout in docker, and it works for me if I add (see added *. in url, it not works without it):

APP_CSP_SCRIPT_SRC="*.myweb.com"

into file:

/docker/freescout/data/config
