### ISSUE TITLE
getFullName() on nul

### ISSUE THREAD

**Issue by ureman2** [freescout-help-desk/freescout#4845]
There are many messages in the log "Call to a member function getFullName() on null (View: /var/www/html/freescout/resources/views/emails/user/notification.blade.php); File: /var/www/html/freescout/app/Thread.php (1360)". And the letter does not go away.
There was already such a thread somewhere, but nothing changed.
Can someone point me in the right direction?

-->

PHP version: 8.2
FreeScout version: 1.8.182
Database: MySQL 
Are you using CloudFlare:  No
Are you using non-official modules:  No
modules: Ldap+ User Fields

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by ureman2** [comment]
> Fixed in the `master` branch and will be published in the next release.

I've already seen exactly the same word here
https://github.com/freescout-help-desk/freescout/issues/3942
a year ago. Probably they didn't fix it completely )

but still, you make a cool product, thank you
